apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mydb
        image: "341422105113.dkr.ecr.us-east-1.amazonaws.com/mysql_image:latest"
        imagePullPolicy: Always
        ports:
        - name: tcp
          containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        hostPath:
      # directory location on host
          path: /data
      # this field is optional
          type: DirectoryOrCreate





---


apiVersion: v1
kind: Service
metadata:
  name: mydb
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql

    
    
